# Site settings
title: He_Define 的博客
description: '我编程三日<br/>两耳不闻人声<br/>只有硬盘在歌唱<br/>'
url: 'http://github.com/HeDefine/HeDefine.github.io'
baseurl: '/'
google_analytics: 'UA-83919014-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Josh Gerdes'
  email: josh@joshgerdes.com
  twitter_username: joshgerdes
  facebook_username: joshgerdes
  github_username:  joshgerdes
  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
